export const techs: Record<string, string> = {
    "wooden_tools": "Wooden Tools",
    "cottage": "Cottage",
    "apartment": "Apartment",
    "oil_power": "Oil Powerplant",
    "club": "Club",
    "bone_tools": "Bone Tools",
    "sundial": "Sundial",
    "wheel": "Wheel",
    "wagon": "Wagon",
    "steam_engine": "Steam Engine",
    "combustion_engine": "Combustion Engine",
    "hover_cart": "Hover Cart",
    "osha": "OSHA Regulations",
    "blackmarket": "Blackmarket",
    "pipelines": "Oil Pipelines",
    "housing": "Housing",
    "arcology": "Arcology",
    "steel_beams": "Steel Beams",
    "mythril_beams": "Mythril Beams",
    "neutronium_walls": "Neutronium Walls",
    "bolognium_alloy_beams": "Bolognium Alloy Beams",
    "aphrodisiac": "Aphrodisiac",
    "fertility_clinic": "Fertility Clinic",
    "captive_housing": "Captive Housing",
    "torture": "Torment",
    "thrall_quarters": "Thrall Quarters",
    "psychic_energy": "Psychic Energy",
    "psychic_attack": "Psychic Assault",
    "psychic_finance": "Psychic Finance",
    "psychic_channeling": "Psychic Channeling",
    "psychic_efficiency": "Psychic Efficiency",
    "mind_break": "Psychic Mind Break",
    "psychic_stun": "Psychic Stun",
    "spear": "Flint Spear",
    "bronze_spear": "Bronze Spear",
    "iron_spear": "Iron Spear",
    "dowsing_rod": "Dowsing Rod",
    "metal_detector": "Metal Detector",
    "smokehouse": "Smokehouse",
    "lodge": "Hunting Lodge",
    "alt_lodge": "Lodge",
    "soul_well": "Soul Well",
    "compost": "Composting",
    "hot_compost": "Hot Composting",
    "mulching": "Mulching",
    "adv_mulching": "Advanced Mulching",
    "agriculture": "Agriculture",
    "farm_house": "Farm Houses",
    "irrigation": "Irrigation",
    "silo": "Grain Silo",
    "mill": "Grain Mill",
    "windmill": "Windmill",
    "windturbine": "Wind Turbine",
    "wind_plant": "Windmill",
    "gmfood": "GM Food",
    "foundry": "Foundry",
    "artisans": "Artisans",
    "apprentices": "Apprentices",
    "carpentry": "Carpentry",
    "demonic_craftsman": "Master Craftsman",
    "master_craftsman": "Master Craftsman",
    "banquet": "Banquet",
    "brickworks": "Brickworks",
    "machinery": "Machinery",
    "cnc_machine": "CNC Machine",
    "vocational_training": "Vocational Training",
    "stellar_forge": "Stellar Forge",
    "stellar_smelting": "Stellar Smelting",
    "assembly_line": "Assembly Line",
    "automation": "Factory Automation",
    "laser_cutters": "Laser Cutters",
    "high_tech_factories": "High-Tech Factory",
    "theatre": "Theatre",
    "playwright": "Playwright",
    "magic": "Techno Wizards",
    "superstars": "Super Stars",
    "radio": "Radio",
    "tv": "Television",
    "vr_center": "VR Center",
    "zoo": "Exotic Zoo",
    "casino": "Casino",
    "dazzle": "Extreme Dazzle",
    "casino_vault": "Casino Vault",
    "otb": "Off Track Betting",
    "online_gambling": "Online Gambling",
    "bolognium_vaults": "Bolognium Vault",
    "mining": "Mining",
    "bayer_process": "Bayer Process",
    "elysis_process": "ELYSIS Process",
    "smelting": "Smelting",
    "steel": "Crucible Steel",
    "blast_furnace": "Blast Furnace",
    "bessemer_process": "Bessemer Process",
    "oxygen_converter": "Oxygen Converter",
    "electric_arc_furnace": "Electric Arc Furnace",
    "hellfire_furnace": "Hellfire Furnace",
    "infernium_fuel": "Infernium Fuel",
    "iridium_smelting_perk": "Iridium Smelting",
    "rotary_kiln": "Rotary Kiln",
    "metal_working": "Metal Working",
    "iron_mining": "Iron Mining",
    "coal_mining": "Coal Mining",
    "storage": "Basic Storage",
    "reinforced_shed": "Reinforced Sheds",
    "barns": "Barns",
    "warehouse": "Warehouse",
    "cameras": "Security Cameras",
    "pocket_dimensions": "Pocket Dimensions",
    "ai_logistics": "AI Shipping Logistics",
    "containerization": "Containerization",
    "reinforced_crates": "Reinforced Crates",
    "cranes": "Cranes",
    "titanium_crates": "Titanium-Banded Crates",
    "mythril_crates": "Mythril-Plated Crates",
    "infernite_crates": "Infernite Crates",
    "graphene_crates": "Graphene Crates",
    "bolognium_crates": "Bolognium Crates",
    "steel_containers": "Steel Containers",
    "gantry_crane": "Gantry Cranes",
    "alloy_containers": "Alloy Containers",
    "mythril_containers": "Mythril Containers",
    "adamantite_containers": "Adamantite Containers",
    "aerogel_containers": "Aerogel Containers",
    "bolognium_containers": "Bolognium Containers",
    "nanoweave_containers": "Nanoweave Liners",
    "evil_planning": "Urban Planning",
    "urban_planning": "Urban Planning",
    "zoning_permits": "Zoning Permits",
    "urbanization": "Urbanization",
    "assistant": "Personal Assistant",
    "government": "Government",
    "theocracy": "Theocracy",
    "republic": "Republic",
    "socialist": "Socialist",
    "corpocracy": "Corpocracy",
    "technocracy": "Technocracy",
    "federation": "Federation",
    "magocracy": "Magocracy",
    "governor": "Governor",
    "spy": "Spies",
    "espionage": "Espionage",
    "spy_training": "Spy Training Facility",
    "spy_gadgets": "Spy Gadgets",
    "code_breakers": "Code Breakers",
    "currency": "Currency",
    "market": "Marketplace",
    "tax_rates": "Tax Rates",
    "large_trades": "Large Volume Trading",
    "corruption": "Corrupt Politicians",
    "massive_trades": "Massive Volume Trading",
    "trade": "Trade Routes",
    "diplomacy": "Diplomacy",
    "freight": "Freight Trains",
    "wharf": "Wharves",
    "banking": "Banking",
    "investing": "Investing",
    "vault": "Bank Vault",
    "bonds": "Savings Bonds",
    "steel_vault": "Steel Vault",
    "eebonds": "Series EE Bonds",
    "swiss_banking": "Cheese Banking",
    "safety_deposit": "Safety Deposit Box",
    "stock_market": "Stock Exchange",
    "hedge_funds": "Hedge Funds",
    "four_oh_one": "401K",
    "exchange": "Galactic Exchange",
    "foreign_investment": "Foreign Investment",
    "mythril_vault": "Mythril Vault",
    "neutronium_vault": "Neutronium Vault",
    "adamantite_vault": "Adamantite Vault",
    "graphene_vault": "Graphene Vault",
    "home_safe": "House Safe",
    "fire_proof_safe": "Fire Proof Safe",
    "tamper_proof_safe": "Tamper Proof Safe",
    "monument": "Monuments",
    "tourism": "Tourism",
    "xeno_tourism": "Xeno Tourism",
    "science": "Scientific Method",
    "library": "Dewey Decimal System",
    "thesis": "Thesis Papers",
    "research_grant": "Research Grants",
    "scientific_journal": "Scientific Journal",
    "adjunct_professor": "Adjunct Professors",
    "tesla_coil": "Tesla Coil",
    "internet": "Internet",
    "observatory": "Space Observatory",
    "world_collider": "World Collider",
    "laboratory": "Laboratory",
    "virtual_assistant": "Virtual Assistant",
    "dimensional_readings": "Dimensional Readings",
    "quantum_entanglement": "Quantum Entanglement",
    "expedition": "Scientific Expeditions",
    "subspace_sensors": "Subspace Sensors",
    "alien_database": "Alien Database",
    "orichalcum_capacitor": "Orichalcum Capacitor",
    "advanced_biotech": "Advanced Biotech",
    "codex_infinium": "Codex Infinium",
    "devilish_dish": "Devilish Dish",
    "hell_oven": "Soul-Vide Cooker",
    "preparation_methods": "Preparation Methods",
    "final_ingredient": "Final Ingredient",
    "bioscience": "Bioscience",
    "genetics": "Genetics",
    "crispr": "CRISPR-Cas9",
    "shotgun_sequencing": "Shotgun Sequencing",
    "de_novo_sequencing": "De Novo Sequencing",
    "dna_sequencer": "DNA Sequencer",
    "rapid_sequencing": "Rapid Gene Sequencing",
    "mad_science": "Mad Science",
    "electricity": "Electricity",
    "matter_replicator": "Matter Replicator",
    "industrialization": "Industrialization",
    "electronics": "Electronics",
    "fission": "Nuclear Fission",
    "arpa": "A.R.P.A.",
    "rocketry": "Rocketry",
    "robotics": "Advanced Robotics",
    "lasers": "Lasers",
    "artifical_intelligence": "Artificial Intelligence",
    "quantum_computing": "Quantum Computing",
    "virtual_reality": "Virtual Reality",
    "plasma": "Plasma Beams",
    "shields": "Energy Shields",
    "ai_core": "AI Supercore",
    "metaphysics": "Metaphysics",
    "orichalcum_analysis": "Orichalcum Analysis",
    "cybernetics": "Cybernetics",
    "blood_pact": "Blood Pact",
    "purify": "Enhanced Air Filters",
    "waygate": "Waygate",
    "demonic_infusion": "Demonic Infusion",
    "gate_key": "Gate Key",
    "gate_turret": "Gate Turret",
    "infernite_mine": "Infernite Survey",
    "study_corrupt_gem": "Study Corrupt Gem",
    "soul_binding": "Soul Binding",
    "soul_capacitor": "Soul Capacitor",
    "absorption_chamber": "Absorption Chamber",
    "corrupt_gem_analysis": "Corrupt Gem Analysis",
    "hell_search": "Search Hell Coordinates",
    "codex_infernium": "Codex Infernium",
    "lake_analysis": "Blood Lake Analysis",
    "lake_threat": "Lake Threat",
    "lake_transport": "Lake Transport",
    "cooling_tower": "Cooling Tower",
    "miasma": "Miasma",
    "incorporeal": "Incorporeal Existence",
    "tech_ascension": "Ascension",
    "terraforming": "Terraforming",
    "cement_processing": "Cement Processing",
    "adamantite_processing_flier": "Adamantite Processing",
    "adamantite_processing": "Adamantite Processing",
    "graphene_processing": "Graphene Processing",
    "fusion_power": "Nuclear Fusion",
    "infernium_power": "Inferno Power",
    "thermomechanics": "Thermomechanics",
    "quantum_manufacturing": "Quantum Manufacturing",
    "worker_drone": "Mining Drones",
    "uranium": "Uranium Extraction",
    "uranium_storage": "Uranium Storage",
    "uranium_ash": "Uranium Ash",
    "breeder_reactor": "Breeder Reactor",
    "mine_conveyor": "Mine Conveyor Belts",
    "oil_well": "Oil Derrick",
    "oil_depot": "Fuel Depot",
    "titanium_drills": "Titanium Drills",
    "alloy_drills": "Alloy Drills",
    "fracking": "Fracking",
    "mythril_drills": "Mythril Drills",
    "mass_driver": "Mass Driver",
    "orichalcum_driver": "Orichalcum Mass Driver",
    "polymer": "Polymer",
    "fluidized_bed_reactor": "Fluidized Bed Reactor",
    "synthetic_fur": "Synthetic Fur",
    "nanoweave": "Nanoweave",
    "stanene": "Stanene",
    "nano_tubes": "Nano Tubes",
    "scarletite": "Scarletite",
    "pillars": "Pillars Research",
    "reclaimer": "Reclaimers",
    "shovel": "Shovel",
    "iron_shovel": "Iron Shovel",
    "steel_shovel": "Steel Shovel",
    "titanium_shovel": "Titanium Shovel",
    "alloy_shovel": "Alloy Shovel",
    "mythril_shovel": "Mythril Shovel",
    "adamantite_shovel": "Adamantite Shovel",
    "stone_axe": "Primitive Axes",
    "copper_axes": "Bronze Axe",
    "iron_saw": "Sawmills",
    "steel_saw": "Steel Saws",
    "iron_axes": "Iron Axe",
    "steel_axes": "Steel Axe",
    "titanium_axes": "Titanium Axe",
    "chainsaws": "Chainsaws",
    "copper_sledgehammer": "Bronze Sledgehammer",
    "iron_sledgehammer": "Iron Sledgehammer",
    "steel_sledgehammer": "Steel Sledgehammer",
    "titanium_sledgehammer": "Titanium Sledgehammer",
    "copper_pickaxe": "Bronze Pickaxe",
    "iron_pickaxe": "Iron Pickaxe",
    "steel_pickaxe": "Steel Pickaxe",
    "jackhammer": "Jackhammer",
    "jackhammer_mk2": "Electric Jackhammer",
    "adamantite_hammer": "Adamantite Jackhammer",
    "copper_hoe": "Bronze Hoes",
    "iron_hoe": "Iron Hoes",
    "steel_hoe": "Steel Hoes",
    "titanium_hoe": "Titanium Hoes",
    "adamantite_hoe": "Adamantite Hoes",
    "cyber_limbs": "Cybernetic Worker Limbs",
    "slave_pens": "Slave Pens",
    "slave_market": "Slave Market",
    "ceremonial_dagger": "Ceremonial Dagger",
    "last_rites": "Last Rites",
    "ancient_infusion": "Ancient Infusion",
    "garrison": "Garrison",
    "mercs": "Mercenaries",
    "signing_bonus": "Signing Bonus",
    "hospital": "Hospital",
    "bac_tanks": "BAC Tank",
    "boot_camp": "Boot Camp",
    "vr_training": "VR Training",
    "bows": "Bows",
    "flintlock_rifle": "Flintlock Rifle",
    "machine_gun": "Machine Gun",
    "bunk_beds": "Bunk Beds",
    "rail_guns": "Rail Guns",
    "laser_rifles": "Laser Rifles",
    "plasma_rifles": "Plasma Rifles",
    "disruptor_rifles": "Disruptor Rifles",
    "gauss_rifles": "Gauss Rifles",
    "cyborg_soldiers": "Cyborg Soldiers",
    "space_marines": "Space Marines",
    "hammocks": "Nanoweave Hammocks",
    "cruiser": "Patrol Cruiser",
    "armor": "Leather Armor",
    "plate_armor": "Plate Armor",
    "kevlar": "Kevlar",
    "nanoweave_vest": "Nanoweave Vest",
    "laser_turret": "Laser Turret",
    "plasma_turret": "Plasma Turret",
    "black_powder": "Black Powder",
    "dynamite": "Dynamite",
    "anfo": "ANFO",
    "mad": "Mutual Destruction",
    "cement": "Cement",
    "rebar": "Rebar",
    "steel_rebar": "Steel Rebar",
    "portland_cement": "Portland Cement",
    "screw_conveyor": "Screw Conveyor",
    "adamantite_screws": "Adamantite Screws",
    "hunter_process": "Hunter Process",
    "kroll_process": "Kroll Process",
    "cambridge_process": "Cambridge Process",
    "pynn_partical": "Pynn Particles",
    "matter_compression": "Matter Compression",
    "higgs_boson": "Higgs Boson",
    "dimensional_compression": "Dimension Compression",
    "theology": "Theology",
    "fanaticism": "Fanaticism",
    "alt_fanaticism": "Fanaticism",
    "ancient_theology": "Ancient Theology",
    "study": "Study Ancients",
    "encoding": "Genetic Encoding",
    "deify": "Deify Ancients",
    "infusion": "Genetic Infusion",
    "indoctrination": "Indoctrination",
    "missionary": "Missionary",
    "zealotry": "Zealotry",
    "anthropology": "Anthropology",
    "alt_anthropology": "Anthropology",
    "mythology": "Mythology",
    "archaeology": "Archaeology",
    "merchandising": "Merchandising",
    "astrophysics": "Astrophysics",
    "rover": "Rovers",
    "probes": "Space Probes",
    "starcharts": "Star Charts",
    "colonization": "Colonization",
    "red_tower": "Red Control Tower",
    "space_manufacturing": "Space Manufacturing",
    "exotic_lab": "Exotic Materials Lab",
    "hydroponics": "Hydroponics Bays",
    "dyson_sphere": "Dyson Sphere",
    "dyson_swarm": "Dyson Swarm",
    "swarm_plant": "Swarm Plant",
    "space_sourced": "Space Sourced",
    "swarm_plant_ai": "Swarm Plant AI",
    "swarm_control_ai": "Swarm Control AI",
    "quantum_swarm": "Quantum Swarm",
    "perovskite_cell": "Perovskite Cells",
    "swarm_convection": "Swarm Convection",
    "orichalcum_panels": "Orichalcum Panels",
    "dyson_net": "Dyson Net",
    "dyson_sphere2": "Dyson Sphere",
    "orichalcum_sphere": "Orichalcum Dyson Plating",
    "gps": "GPS Constellation",
    "nav_beacon": "Navigation Beacon",
    "subspace_signal": "Subspace Beacon",
    "atmospheric_mining": "Atmospheric Mining",
    "helium_attractor": "Helium Attractor",
    "ram_scoops": "Ram Scoops",
    "elerium_prospecting": "Elerium Prospecting",
    "zero_g_mining": "Zero G Mining",
    "elerium_mining": "Elerium Mining",
    "laser_mining": "Laser Mining",
    "plasma_mining": "Plasma Mining",
    "elerium_tech": "Elerium Theory",
    "elerium_reactor": "Elerium Reactor",
    "neutronium_housing": "Neutronium Housing",
    "unification": "Unification",
    "unification2": "Unification",
    "unite": "Unite Country",
    "genesis": "Genesis Project",
    "star_dock": "Space Dock",
    "interstellar": "Interstellar Probes",
    "genesis_ship": "Genesis Ship",
    "geck": "G.E.C.K.",
    "genetic_decay": "Gene Therapy",
    "stabilize_decay": "Stabilize Decay",
    "tachyon": "Tachyon Particles",
    "warp_drive": "Alcubierre Drive",
    "habitat": "Habitat",
    "graphene": "Graphene",
    "aerogel": "Aerogel",
    "mega_manufacturing": "Mega Manufacturing",
    "luxury_condo": "Luxury Condo",
    "stellar_engine": "Stellar Engine",
    "mass_ejector": "Mass Ejector",
    "asteroid_redirect": "Asteroid Redirect",
    "exotic_infusion": "Exotic Infusion",
    "infusion_check": "Exotic Infusion",
    "infusion_confirm": "Exotic Infusion",
    "stabilize_blackhole": "Stabilize Black Hole",
    "veil": "The Veil",
    "mana_syphon": "Mana Syphon",
    "gravitational_waves": "Gravitational Waves",
    "gravity_convection": "Gravitational Convection",
    "wormholes": "Wormholes",
    "portal": "Portals",
    "fortifications": "Fortifications",
    "war_drones": "War Drones",
    "demon_attractor": "Demonic Attractor",
    "combat_droids": "Combat Droids",
    "repair_droids": "Repair Droids",
    "advanced_predators": "Advanced Drones",
    "enhanced_droids": "Enhanced War Droids",
    "sensor_drone": "Sensor Drones",
    "map_terrain": "Map Terrain",
    "calibrated_sensors": "Calibrated Sensors",
    "shield_generator": "Shield Generator",
    "enhanced_sensors": "Enhanced Sensors",
    "xeno_linguistics": "Xeno Linguistics",
    "xeno_culture": "Xeno Culture",
    "cultural_exchange": "Cultural Exchange",
    "shore_leave": "Shore Leave",
    "xeno_gift": "Alien Gift",
    "industrial_partnership": "Industrial Partnership",
    "embassy_housing": "Embassy Housing",
    "advanced_telemetry": "Advanced Telemetry",
    "defense_platform": "Defense Platform",
    "scout_ship": "Scout Ship",
    "corvette_ship": "Corvette Ship",
    "frigate_ship": "Frigate Ship",
    "cruiser_ship": "Cruiser Ship",
    "dreadnought": "Dreadnought",
    "ship_dock": "Ship Dock",
    "ore_processor": "Ore Processor",
    "scavenger": "Tech Scavenger",
    "coordinates": "Decrypt Coordinates",
    "chthonian_survey": "Chthonian Survey",
    "gateway_depot": "Depot",
    "soul_forge": "Soul Forge",
    "soul_attractor": "Soul Attractor",
    "soul_absorption": "Soul Absorption",
    "soul_link": "Soul Link",
    "gun_emplacement": "Gun Emplacement",
    "advanced_emplacement": "Advanced Gun Emplacement",
    "dial_it_to_11": "Dial it up to 11",
    "limit_collider": "Limit Collider",
    "mana": "Mana",
    "ley_lines": "Ley Lines",
    "rituals": "Rituals",
    "crafting_ritual": "Crafting Rituals",
    "mana_nexus": "Mana Nexus",
    "clerics": "Clerics",
    "conjuring": "Conjuring",
    "res_conjuring": "Resource Conjuring",
    "alchemy": "Alchemy",
    "transmutation": "Advanced Transmutation",
    "secret_society": "Secret Society",
    "cultists": "Cultists",
    "conceal_ward": "Concealing Wards",
    "subtle_rituals": "Subtle Rituals",
    "pylon_camouflage": "Pylon Camouflage",
    "fake_tech": "Fake Tech",
    "concealment": "Empowered Concealment Wards",
    "improved_concealment": "Improved Concealment Wards",
    "outerplane_summon": "Outerplane Summon",
    "dark_bomb": "Dark Energy Bomb",
    "bribe_sphinx": "Bribe Sphinx",
    "alien_biotech": "Alien Biotech",
    "zero_g_lab": "Zero Gravity Lab",
    "operating_base": "Operating Base",
    "munitions_depot": "Munitions Depot",
    "fob": "Forward Operating Base",
    "bac_tanks_tp": "BAC Tank",
    "medkit": "Advanced Medkits",
    "sam_site": "Planetary Defenses",
    "data_cracker": "Data Cracker",
    "ai_core_tp": "AI Supercore",
    "ai_optimizations": "AI Optimizations",
    "synthetic_life": "Synthetic Life",
    "protocol66": "Protocol 66",
    "protocol66a": "Protocol 66",
    "terraforming_tp": "Terraforming",
    "quantium": "Quantium",
    "anitgrav_bunk": "Anti-Grav Bunks",
    "higgs_boson_tp": "Higgs Boson",
    "long_range_probes": "Long Range Probes",
    "strange_signal": "Strange Signal",
    "data_analysis": "Encrypted Data Analysis",
    "mass_relay": "Mass Relay",
    "nav_data": "Navigation Data",
    "sensor_logs": "Tau Ceti Data",
    "dronewar": "Drone Warfare",
    "drone_tank": "AI Drone Tanks",
    "stanene_tp": "Stanene",
    "graphene_tp": "Graphene",
    "virtual_reality_tp": "Virtual Reality",
    "electrolysis": "Electrolysis",
    "storehouse": "Titan Storage Facility",
    "adamantite_vault_tp": "Adamantite Vault",
    "titan_bank": "Titan Banking",
    "hydrogen_plant": "Hydrogen Power",
    "water_mining": "Water Mining",
    "mercury_smelting": "Solar Smelting",
    "iridium_smelting": "Iridium Smelting",
    "adamantite_crates": "Adamantite Crates",
    "bolognium_crates_tp": "Bolognium Crates",
    "adamantite_containers_tp": "Adamantite Containers",
    "quantium_containers": "Quantium Containers",
    "unobtainium_containers": "Unobtainium Containers",
    "reinforced_shelving": "Reinforced Shelving",
    "garage_shelving": "Quantium Garage Shelving",
    "warehouse_shelving": "Automated Warehousing System",
    "elerium_extraction": "Elerium Extraction",
    "orichalcum_panels_tp": "Orichalcum Panels",
    "shipyard": "Dwarf Ship Yard",
    "ship_lasers": "Ship Lasers",
    "pulse_lasers": "Ship Pulse Lasers",
    "ship_plasma": "Ship Plasma Beams",
    "ship_phaser": "Ship Phasers",
    "ship_disruptor": "Ship Disruptor",
    "destroyer_ship": "Destroyer",
    "cruiser_ship_tp": "Cruiser",
    "h_cruiser_ship": "Battlecruiser",
    "dreadnought_ship": "Dreadnought",
    "pulse_engine": "Pulse Drive",
    "photon_engine": "Photon Drive",
    "vacuum_drive": "Vacuum Drive",
    "ship_fusion": "Fusion Generator",
    "ship_elerium": "Elerium Generator",
    "quantum_signatures": "Quantum Signatures",
    "interstellar_drive": "Interstellar Drive",
    "alien_outpost": "Alien Outpost",
    "jumpgates": "Jump Gates",
    "system_survey": "Tau Survey",
    "repository": "Repository",
    "fusion_generator": "Nuclear Fusion",
    "tau_cultivation": "Tau Ceti Cultivation",
    "tau_manufacturing": "Tau Ceti Manufacturing",
    "weasels": "Weasels",
    "jeff": "Contact Jeff",
    "womling_fun": "Womling Entertainment",
    "womling_lab": "Womling Science",
    "womling_mining": "Womling Dirt Excavation",
    "womling_firstaid": "Womling First Aid",
    "womling_logistics": "Womling Logistics",
    "womling_repulser": "Womling Repulser Pad",
    "womling_farming": "Womling Farming",
    "womling_housing": "Womling Housing",
    "womling_support": "Womling Support",
    "womling_recycling": "Womling Recycling",
    "asteroid_analysis": "Asteroid Data Analysis",
    "shark_repellent": "Shark Repellent",
    "belt_mining": "Tau Ceti Belt Mining",
    "adv_belt_mining": "Advanced Belt Mining",
    "space_whaling": "Space Whaling",
    "infectious_disease_lab": "Infectious Disease Lab",
    "isolation_protocol": "Isolation Protocol",
    "focus_cure": "Focus Cure",
    "decode_virus": "Decode Virus",
    "vaccine_campaign": "Vaccination Campaign",
    "vax_strat1": "Propaganda Campaign",
    "vax_strat2": "Force Vaccination",
    "vax_strat3": "Show the Science",
    "vax_strat4": "Secret Vaccination",
    "cloning": "Cloning Facility",
    "clone_degradation": "Clone Degradation",
    "digital_paradise": "Digital Paradise",
    "ringworld": "Design a Ringworld",
    "iso_gambling": "Pit Bosses",
    "outpost_boost": "Alien Outpost Device",
    "cultural_center": "Cultural Center",
    "outer_tau_survey": "Survey Outer Planet",
    "alien_research": "Alien Research",
    "womling_gene_therapy": "Womling Gene Therapy",
    "food_culture": "Sell fruitcake",
    "advanced_refinery": "Advanced Ore Refinery",
    "advanced_pit_mining": "Advanced Pit Mining",
    "useless_junk": "Useless Junk",
    "advanced_asteroid_mining": "Advanced Asteroid Mining",
    "advanced_material_synthesis": "Advanced Material Synthesis",
    "matrioshka_brain": "Matrioshka Brain",
    "ignition_device": "Ignition Device",
    "replicator": "Matter Replicator",
    "womling_unlock": "Meet The Neighbors",
    "garden_of_eden": "Garden of Eden",
};
