export type ResearchInfo = {
    era: string,
    name: string,
    suffix?: string
}

type SourceInfo = Record<string, Record<string, string | { name: string, suffix: string }>>;

function makeTechInfo(data: SourceInfo): Record<string, ResearchInfo> {
    const entries: Record<string, ResearchInfo> = {};

    for (const [era, techs] of Object.entries(data)) {
        for (const [id, entry] of Object.entries(techs)) {
            entries[id] = entry instanceof Object ? { era, ...entry } : { era, name: entry };
        }
    }

    return entries;
}

export const techs = makeTechInfo({
    "Primitive": {
        club: "Club",
        bone_tools: { name: "Bone Tools", suffix: "Evil" },
        wooden_tools: "Wooden Tools",
        sundial: "Sundial",
        wheel: { name: "Wheel", suffix: "Gravity Well" }
    },
    "Civilized": {
        wagon: { name: "Wagon", suffix: "Gravity Well" },
        housing: "Housing",
        cottage: "Cottage",
        aphrodisiac: "Aphrodisiac",
        captive_housing: { name: "Captive Housing", suffix: "Unfathomable" },
        torture: { name: "Torment", suffix: "Unfathomable" },
        thrall_quarters: { name: "Thrall Quarters", suffix: "Unfathomable" },
        minor_wish: { name: "Limited Wish", suffix: "Wish" },
        major_wish: { name: "Greater Wish", suffix: "Wish" },
        psychic_energy: { name: "Psychic Energy", suffix: "Psychic" },
        psychic_attack: { name: "Psychic Assault", suffix: "Psychic" },
        psychic_finance: { name: "Psychic Finance", suffix: "Psychic" },
        mind_break: { name: "Psychic Mind Break", suffix: "Psychic" },
        psychic_stun: { name: "Psychic Stun", suffix: "Psychic" },
        spear: { name: "Flint Spear", suffix: "Forager" },
        bronze_spear: { name: "Bronze Spear", suffix: "Forager" },
        iron_spear: { name: "Iron Spear", suffix: "Forager" },
        dowsing_rod: { name: "Dowsing Rod", suffix: "Forager" },
        metal_detector: { name: "Metal Detector", suffix: "Forager" },
        smokehouse: { name: "Smokehouse", suffix: "Carnivore" },
        lodge: { name: "Hunting Lodge", suffix: "Carnivore" },
        alt_lodge: "Lodge",
        soul_well: { name: "Soul Well", suffix: "Soul Eater" },
        compost: { name: "Composting", suffix: "Detritivore" },
        hot_compost: { name: "Hot Composting", suffix: "Detritivore" },
        mulching: { name: "Mulching", suffix: "Detritivore" },
        agriculture: "Agriculture",
        farm_house: "Farm Houses",
        irrigation: "Irrigation",
        silo: "Grain Silo",
        mill: "Grain Mill",
        foundry: "Foundry",
        artisans: "Artisans",
        apprentices: "Apprentices",
        carpentry: "Carpentry",
        theatre: "Theatre",
        playwright: "Playwright",
        mining: "Mining",
        bayer_process: "Bayer Process",
        smelting: "Smelting",
        steel: "Crucible Steel",
        metal_working: "Metal Working",
        iron_mining: "Iron Mining",
        coal_mining: "Coal Mining",
        storage: "Basic Storage",
        reinforced_shed: "Reinforced Sheds",
        containerization: "Containerization",
        reinforced_crates: "Reinforced Crates",
        evil_planning: { name: "Urban Planning", suffix: "Terrifying" },
        urban_planning: "Urban Planning",
        assistant: "Personal Assistant",
        government: "Government",
        theocracy: "Theocracy",
        governor: "Governor",
        spy: "Spies",
        currency: "Currency",
        market: "Marketplace",
        tax_rates: "Tax Rates",
        large_trades: "Large Volume Trading",
        trade: "Trade Routes",
        banking: "Banking",
        investing: "Investing",
        vault: "Bank Vault",
        bonds: "Savings Bonds",
        steel_vault: "Steel Vault",
        science: "Scientific Method",
        library: "Dewey Decimal System",
        thesis: "Thesis Papers",
        research_grant: "Research Grant",
        reclaimer: { name: "Reclaimers", suffix: "Evil" },
        shovel: { name: "Shovel", suffix: "Evil" },
        iron_shovel: { name: "Iron Shovel", suffix: "Evil" },
        stone_axe: "Primitive Axes",
        copper_axes: "Bronze Axe",
        iron_saw: "Sawmills",
        iron_axes: "Iron Axe",
        copper_sledgehammer: "Bronze Sledgehammer",
        iron_sledgehammer: "Iron Sledgehammer",
        copper_pickaxe: "Bronze Pickaxe",
        iron_pickaxe: "Iron Pickaxe",
        copper_hoe: "Bronze Hoes",
        iron_hoe: "Iron Hoes",
        slave_pens: { name: "Slave Pen", suffix: "Slaver" },
        ceremonial_dagger: { name: "Ceremonial Dagger", suffix: "Cannibalize" },
        last_rites: { name: "Last Rites", suffix: "Cannibalize" },
        garrison: "Garrison",
        mercs: "Mercenaries",
        hospital: "Hospital",
        bows: "Bows",
        flintlock_rifle: "Flintlock Rifle",
        armor: "Leather Armor",
        plate_armor: "Plate Armor",
        black_powder: "Black Powder",
        dynamite: "Dynamite",
        cement: "Cement",
        rebar: "Rebar",
        steel_rebar: "Steel Rebar",
        theology: "Theology",
        fanaticism: "Fanaticism",
        alt_fanaticism: { name: "Fanaticism", suffix: "Post-Transcendence" },
        indoctrination: "Indoctrination",
        anthropology: "Anthropology",
        alt_anthropology: { name: "Anthropology", suffix: "Post-Transcendence" },
        mythology: "Mythology",
        mana: "Mana",
        ley_lines: "Ley Lines",
        rituals: "Rituals",
        clerics: "Clerics",
        conjuring: "Conjuring",
        res_conjuring: "Resource Conjuring",
        secret_society: "Secret Society",
        cultists: { name: "Cultists", suffix: "Witch Hunter" },
        might: "Might Makes Right"
    },
    "Discovery": {
        steam_engine: { name: "Steam Engine", suffix: "Gravity Well" },
        apartment: "Apartment",
        steel_beams: "Steel Beams",
        adv_mulching: { name: "Advanced Mulching", suffix: "Detritivore" },
        windmill: "Windmill",
        demonic_craftsman: { name: "Master Crafter", suffix: "Evil" },
        master_craftsman: "Master Crafter",
        brickworks: "Brickworks",
        banquet: "Banquet",
        magic: "Techno Wizards",
        radio: "Radio",
        blast_furnace: "Blast Furnace",
        bessemer_process: "Bessemer Process",
        barns: "Barns",
        cranes: "Cranes",
        steel_containers: "Steel Containers",
        gantry_crane: "Gantry Cranes",
        republic: "Republic",
        socialist: "Socialist",
        espionage: "Espionage",
        spy_training: "Spy Training Facility",
        spy_gadgets: "Spy Gadgets",
        diplomacy: "Diplomacy",
        eebonds: "Series EE Bonds",
        home_safe: "House Safe",
        mad_science: "Mad Science",
        electricity: "Electricity",
        matter_replicator: "Matter Replicator",
        mine_conveyor: "Mine Conveyor Belts",
        steel_shovel: { name: "Steel Shovel", suffix: "Evil" },
        steel_saw: "Steel Saws",
        steel_axes: "Steel Axe",
        steel_sledgehammer: "Steel Sledgehammer",
        steel_pickaxe: "Steel Pickaxe",
        jackhammer: "Jackhammer",
        steel_hoe: "Steel Hoes",
        slave_market: { name: "Slave Market", suffix: "Slaver" },
        boot_camp: "Boot Camp",
        missionary: "Missionary",
        zealotry: "Zealotry",
        archaeology: "Archaeology",
        merchandising: "Merchandising",
        crafting_ritual: "Crafting Rituals",
        alchemy: "Alchemy",
        conceal_ward: { name: "Concealing Wards", suffix: "Witch Hunter" },
        subtle_rituals: { name: "Subtle Rituals", suffix: "Witch Hunter" }
    },
    "Industrialized": {
        combustion_engine: { name: "Combustion Engine", suffix: "Gravity Well" },
        osha: { name: "OSHA Regulations", suffix: "Gravity Well" },
        blackmarket: { name: "Blackmarket", suffix: "Gravity Well" },
        vocational_training: "Vocational Training",
        oxygen_converter: "Oxygen Converter",
        rotary_kiln: "Rotary Kiln",
        warehouse: "Warehouse",
        alloy_containers: "Alloy Containers",
        zoning_permits: "Zoning Permits",
        corpocracy: "Corpocracy",
        technocracy: "Technocracy",
        magocracy: "Magocracy",
        code_breakers: "Code Breakers",
        corruption: "Corrupt Politicians",
        freight: "Freight Trains",
        wharf: "Wharves",
        swiss_banking: "Swiss Banking",
        scientific_journal: "Scientific Journal",
        adjunct_professor: "Adjunct Professors",
        tesla_coil: "Tesla Coil",
        industrialization: "Industrialization",
        electronics: "Electronics",
        thermomechanics: "Thermomechanics",
        oil_well: "Oil Derrick",
        oil_depot: "Fuel Depot",
        oil_power: "Oil Powerplant",
        titanium_drills: "Titanium Drills",
        titanium_shovel: { name: "Titanium Shovel", suffix: "Evil" },
        titanium_axes: "Titanium Axe",
        titanium_sledgehammer: "Titanium Sledgehammer",
        titanium_hoe: "Titanium Hoes",
        signing_bonus: "Signing Bonus",
        machine_gun: "Machine Gun",
        anfo: "ANFO",
        portland_cement: "Portland Cement",
        hunter_process: "Hunter Process",
        pylon_camouflage: { name: "Pylon Camouflage", suffix: "Witch Hunter" },
        fake_tech: { name: "Fake Tech", suffix: "Witch Hunter" },
        executions: "Public Executions"
    },
    "Deep Space": {
        hover_cart: { name: "Hover Cart", suffix: "Gravity Well" },
        neutronium_walls: "Neutronium Walls",
        psychic_channeling: { name: "Psychic Channeling", suffix: "Psychic" },
        laser_cutters: "Laser Cutters",
        otb: "Off Track Betting",
        neutronium_vault: "Neutronium Vault",
        world_collider: "World Collider",
        dna_sequencer: "DNA Sequencer",
        lasers: "Lasers",
        artifical_intelligence: "Artificial Intelligence",
        quantum_computing: "Quantum Computing",
        quantum_manufacturing: "Quantum Manufacturing",
        worker_drone: "Mining Drones",
        nano_tubes: "Nano Tubes",
        laser_rifles: "Laser Rifles",
        encoding: "Genetic Encoding",
        infusion: "Genetic Infusion",
        exotic_lab: "Exotic Materials Lab",
        swarm_plant: "Swarm Plant",
        space_sourced: "Space Sourced",
        swarm_plant_ai: "Swarm Plant AI",
        swarm_control_ai: "Swarm Control AI",
        quantum_swarm: "Quantum Swarm",
        helium_attractor: "Helium Attractor",
        elerium_mining: "Elerium Mining",
        laser_mining: "Laser Mining",
        elerium_tech: "Elerium Theory",
        elerium_reactor: "Elerium Reactor",
        neutronium_housing: "Neutronium Housing",
        genesis: "Genesis Project",
        star_dock: "Space Dock",
        interstellar: "Interstellar Probes",
        genesis_ship: "Genesis Ship",
        geck: "G.E.C.K.",
        dial_it_to_11: "Dial it up to 11",
        limit_collider: "Limit Collider",
        ai_tracking: "Facial Recognition"
    },
    "Globalized": {
        pipelines: { name: "Oil Pipelines", suffix: "Gravity Well" },
        windturbine: "Wind Turbine",
        wind_plant: { name: "Windmill", suffix: "Power Plant" },
        gmfood: "GM Food",
        machinery: "Machinery",
        cnc_machine: "CNC Machine",
        assembly_line: "Assembly Line",
        tv: "Television",
        casino: "Casino",
        dazzle: "Extreme Dazzle",
        electric_arc_furnace: "Electric Arc Furnace",
        cameras: "Security Cameras",
        titanium_crates: "Titanium-Banded Crates",
        urbanization: "Urbanization",
        massive_trades: "Massive Volume Trading",
        safety_deposit: "Safety Deposit Box",
        stock_market: "Stock Exchange",
        monument: "Monuments",
        internet: "Internet",
        bioscience: "Bioscience",
        genetics: "Genetics",
        crispr: "CRISPR-Cas9",
        fission: "Nuclear Fission",
        arpa: "A.R.P.A.",
        rocketry: "Rocketry",
        robotics: "Advanced Robotics",
        uranium: "Uranium Extraction",
        uranium_storage: "Uranium Storage",
        uranium_ash: "Uranium Ash",
        alloy_drills: "Alloy Drills",
        fracking: "Fracking",
        polymer: "Polymer",
        fluidized_bed_reactor: "Fluidized Bed Reactor",
        synthetic_fur: "Synthetic Fur",
        alloy_shovel: { name: "Alloy Shovel", suffix: "Evil" },
        jackhammer_mk2: "Electric Jackhammer",
        bunk_beds: "Bunk Beds",
        kevlar: "Kevlar",
        mad: "Mutual Destruction",
        screw_conveyor: "Screw Conveyor",
        kroll_process: "Kroll Process",
        unite: { name: "Unite Country", suffix: "True Path" },
        secret_police: "Secret Police"
    },
    "Dimensional": {
        arcology: "Arcology",
        zoo: "Exotic Zoo",
        infernium_fuel: "Infernium Fuel",
        advanced_biotech: "Advanced Biotech",
        codex_infinium: "Codex Infinium",
        devilish_dish: { name: "Devilish Dish", suffix: "Fasting" },
        hell_oven: { name: "Soul-Vide Cooker", suffix: "Fasting" },
        preparation_methods: { name: "Preparation Methods", suffix: "Fasting" },
        final_ingredient: { name: "Final Ingredient", suffix: "Fasting" },
        cybernetics: "Cybernetics",
        blood_pact: "Blood Pact",
        purify: "Enhanced Air Filters",
        waygate: "Waygate",
        demonic_infusion: "Demonic Infusion",
        gate_key: "Gate Key",
        gate_turret: "Gate Turret",
        infernite_mine: "Infernite Survey",
        corrupt_gem_analysis: "Corrupt Gem Analysis",
        hell_search: "Search Hell Coordinates",
        codex_infernium: "Codex Infernium",
        lake_analysis: "Blood Lake Analysis",
        lake_threat: "Lake Threat",
        lake_transport: "Lake Transport",
        cooling_tower: "Cooling Tower",
        miasma: "Miasma",
        infernium_power: "Inferno Power",
        scarletite: "Scarletite",
        pillars: "Pillars Research",
        cyber_limbs: "Cybernetic Worker Limbs",
        cyborg_soldiers: "Cyborg Soldiers",
        stabilize_decay: "Stabilize Decay",
        outerplane_summon: { name: "Outerplane Summon", suffix: "Witch Hunter" },
        dark_bomb: "Dark Energy Bomb",
        bribe_sphinx: "Bribe Sphinx"
    },
    "Early Space": {
        mythril_beams: "Mythril Beams",
        automation: "Factory Automation",
        casino_vault: "Casino Vault",
        iridium_smelting_perk: "Iridium Smelting",
        pocket_dimensions: "Pocket Dimensions",
        mythril_crates: "Mythril-Plated Crates",
        mythril_containers: "Mythril Containers",
        federation: "Federation",
        hedge_funds: "Hedge Funds",
        four_oh_one: "401K",
        mythril_vault: "Mythril Vault",
        fire_proof_safe: "Fire Proof Safe",
        tourism: "Tourism",
        observatory: "Space Observatory",
        shotgun_sequencing: "Shotgun Sequencing",
        de_novo_sequencing: "De Novo Sequencing",
        breeder_reactor: "Breeder Reactor",
        mythril_drills: "Mythril Drills",
        mass_driver: "Mass Driver",
        mythril_shovel: { name: "Mythril Shovel", suffix: "Evil" },
        ancient_infusion: { name: "Ancient Infusion", suffix: "Cannibalize" },
        rail_guns: "Rail Guns",
        space_marines: "Space Marines",
        cambridge_process: "Cambridge Process",
        pynn_partical: "Pynn Particles",
        matter_compression: "Matter Compression",
        higgs_boson: "Higgs Boson",
        ancient_theology: "Ancient Theology",
        study: "Study Ancients",
        study_alt: { name: "Study Ancients", suffix: "Post-Preeminence" },
        deify: "Deify Ancients",
        deify_alt: { name: "Deify Ancients", suffix: "Post-Preeminence" },
        astrophysics: "Astrophysics",
        rover: "Rovers",
        probes: "Space Probes",
        starcharts: "Star Charts",
        colonization: "Colonization",
        red_tower: "Mars Control Tower",
        space_manufacturing: "Space Manufacturing",
        dyson_sphere: { name: "Dyson Sphere", suffix: "Plans" },
        dyson_swarm: "Dyson Swarm",
        gps: "GPS Constellation",
        nav_beacon: "Navigation Beacon",
        atmospheric_mining: "Atmospheric Mining",
        zero_g_mining: "Zero G Mining",
        unification: { name: "Unification", suffix: "Plans" },
        unification2: "Unification",
        genetic_decay: "Gene Therapy",
        mana_nexus: "Mana Nexus",
        concealment: { name: "Empowered Concealment Wards", suffix: "Witch Hunter" },
        higgs_boson_tp: { name: "Higgs Boson", suffix: "True Path" }
    },
    "Intergalactic": {
        bolognium_alloy_beams: "Bolognium Alloy Beams",
        fertility_clinic: "Fertility Clinic",
        psychic_efficiency: { name: "Psychic Efficiency", suffix: "Psychic" },
        stellar_forge: "Stellar Forge",
        stellar_smelting: "Stellar Smelting",
        high_tech_factories: "High-Tech Factory",
        bolognium_vaults: "Bolognium Vault",
        bolognium_crates: "Bolognium Crates",
        bolognium_containers: "Bolognium Containers",
        nanoweave_containers: "Nanoweave Liners",
        foreign_investment: "Foreign Investment",
        xeno_tourism: "Xeno Tourism",
        expedition: "Scientific Expeditions",
        subspace_sensors: "Subspace Sensors",
        alien_database: "Alien Database",
        orichalcum_capacitor: "Orichalcum Capacitor",
        metaphysics: "Metaphysics",
        orichalcum_analysis: "Orichalcum Analysis",
        study_corrupt_gem: { name: "Study Corrupt Gem", suffix: "Witch Hunter" },
        soul_binding: { name: "Soul Binding", suffix: "Witch Hunter" },
        soul_capacitor: { name: "Soul Capacitor", suffix: "Witch Hunter" },
        absorption_chamber: { name: "Absorption Chamber", suffix: "Witch Hunter" },
        incorporeal: "Incorporeal Existence",
        tech_ascension: "Ascension",
        terraforming: { name: "Terraforming", suffix: "Orbital Decay" },
        graphene_processing: "Graphene Processing",
        orichalcum_driver: "Orichalcum Mass Driver",
        nanoweave: "Nanoweave",
        gauss_rifles: "Gauss Rifles",
        hammocks: "Nanoweave Hammocks",
        nanoweave_vest: "Nanoweave Vest",
        hydroponics: "Hydroponics Bays",
        orichalcum_panels: "Orichalcum Panels",
        dyson_sphere2: "Dyson Sphere",
        orichalcum_sphere: "Orichalcum Dyson Plating",
        mega_manufacturing: "Mega Manufacturing",
        luxury_condo: "Luxury Condo",
        asteroid_redirect: "Asteroid Redirect",
        wormholes: "Wormholes",
        advanced_predators: "Advanced Drones",
        shield_generator: "Shield Generator",
        enhanced_sensors: "Enhanced Sensors",
        xeno_linguistics: "Xeno Linguistics",
        xeno_culture: "Xeno Culture",
        cultural_exchange: "Cultural Exchange",
        shore_leave: "Shore Leave",
        xeno_gift: "Alien Gift",
        industrial_partnership: "Industrial Partnership",
        embassy_housing: "Embassy Housing",
        advanced_telemetry: "Advanced Telemetry",
        defense_platform: "Defense Platform",
        scout_ship: "Scout Ship",
        corvette_ship: "Corvette Ship",
        frigate_ship: "Frigate Ship",
        cruiser_ship: "Cruiser Ship",
        dreadnought: "Dreadnought",
        ship_dock: "Ship Dock",
        ore_processor: "Ore Processor",
        scavenger: "Tech Scavenger",
        coordinates: "Decrypt Coordinates",
        chthonian_survey: "Chthonian Survey",
        gateway_depot: "Depot",
        soul_forge: "Soul Forge",
        soul_attractor: "Soul Attractor",
        soul_absorption: "Soul Absorption",
        soul_link: "Soul Link",
        gun_emplacement: "Gun Emplacement",
        advanced_emplacement: "Advanced Gun Emplacement",
        transmutation: "Advanced Transmutation",
        improved_concealment: { name: "Improved Concealment Wards", suffix: "Witch Hunter" },
        predictive_arrests: "Predictive Arrests"
    },
    "Interstellar": {
        superstars: "Super Stars",
        vr_center: "VR Center",
        online_gambling: "Online Gambling",
        elysis_process: "ELYSIS Process",
        hellfire_furnace: "Hellfire Furnace",
        ai_logistics: "AI Shipping Logistics",
        infernite_crates: "Infernite Crates",
        graphene_crates: "Graphene Crates",
        adamantite_containers: "Adamantite Containers",
        aerogel_containers: "Aerogel Containers",
        exchange: "Galactic Exchange",
        adamantite_vault: "Adamantite Vault",
        graphene_vault: "Graphene Vault",
        tamper_proof_safe: "Tamper Proof Safe",
        laboratory: "Laboratory",
        virtual_assistant: "Virtual Assistant",
        dimensional_readings: "Dimensional Readings",
        quantum_entanglement: "Quantum Entanglement",
        rapid_sequencing: "Rapid Gene Sequencing",
        virtual_reality: "Virtual Reality",
        plasma: "Plasma Beams",
        shields: "Energy Shields",
        ai_core: "AI Supercore",
        cement_processing: "Cement Processing",
        adamantite_processing_flier: { name: "Adamantite Processing", suffix: "Flier" },
        adamantite_processing: "Adamantite Processing",
        fusion_power: "Nuclear Fusion",
        stanene: "Stanene",
        adamantite_shovel: { name: "Adamantite Shovel", suffix: "Evil" },
        chainsaws: "Chainsaws",
        adamantite_hammer: "Adamantite Jackhammer",
        adamantite_hoe: "Adamantite Hoes",
        bac_tanks: "BAC Tank",
        vr_training: "VR Training",
        plasma_rifles: "Plasma Rifles",
        disruptor_rifles: "Disruptor Rifles",
        cruiser: "Patrol Cruiser",
        laser_turret: "Laser Turret",
        plasma_turret: "Plasma Turret",
        adamantite_screws: "Adamantite Screws",
        dimensional_compression: "Dimension Compression",
        perovskite_cell: "Perovskite Cells",
        swarm_convection: "Swarm Convection",
        dyson_net: "Dyson Net",
        subspace_signal: "Subspace Beacon",
        ram_scoops: "Ram Scoops",
        elerium_prospecting: "Elerium Prospecting",
        plasma_mining: "Plasma Mining",
        tachyon: "Tachyon Particles",
        warp_drive: "Alcubierre Drive",
        habitat: "Habitat",
        graphene: "Graphene",
        aerogel: "Aerogel",
        stellar_engine: "Stellar Engine",
        mass_ejector: "Mass Ejector",
        exotic_infusion: { name: "Exotic Infusion", suffix: "1st Warning" },
        infusion_check: { name: "Exotic Infusion", suffix: "2nd Warning" },
        infusion_confirm: "Exotic Infusion",
        stabilize_blackhole: "Stabilize Black Hole",
        veil: "The Veil",
        mana_syphon: "Mana Syphon",
        gravitational_waves: "Gravitational Waves",
        gravity_convection: "Gravitational Convection",
        portal: "Portals",
        fortifications: "Fortifications",
        war_drones: "War Drones",
        demon_attractor: "Demonic Attractor",
        combat_droids: "Combat Droids",
        repair_droids: "Repair Droids",
        enhanced_droids: "Enhanced War Droids",
        sensor_drone: "Sensor Drones",
        map_terrain: "Map Terrain",
        calibrated_sensors: "Calibrated Sensors"
    },
    "Existential": {
        elysanite_crates: "Elysanite Crates",
        elysanite_containers: "Elysanite Containers",
        crypto_currency: "Crypto Currency",
        spirit_box: "Spirit Box",
        spirit_researcher: "Occult Researcher",
        dimensional_tap: "Dimensional Tap",
        divinity: "Divine Providence",
        purify_essence: "Purify Essence",
        crypto_mining: "Crypto Mining",
        elysanite_hammer: "Elysanite Jackhammer",
        ethereal_weapons: "Ethereal Weaponry",
        super_tnt: "Super TNT",
        otherworldly_binder: "Otherworldly Binder",
        elysanite_sphere: "Elysanite Dyson Paneling",
        soul_bait: "Soul Bait",
        asphodel_flowers: "Ghostly Flowers",
        ghost_traps: "Ghost Traps",
        research_station: "Non-overlapping Magisteria",
        soul_engine: "Soul Power",
        railway_to_hell: "Railway to Hell",
        purification: "Purification",
        asphodel_mech: "Asphodel Mech Security",
        asphodel_storage: "Asphodel Storage",
        asphodel_stabilizer: "Asphodel Stabilizer",
        edenic_bunker: "Edenic Bunker",
        bliss_den: "Den of Bliss",
        hallowed_housing: "Hallowed Housing",
        outer_plane_study: "Outer Plane Study",
        camouflage: "Camouflage",
        celestial_tactics: "Celestial Tactics",
        active_camouflage: "Active Camouflage",
        special_ops_training: "Special Ops Training",
        spectral_training: "Spectral Training Ground",
        elysanite_mining: "Elysanite Mining",
        sacred_smelter: "Sacred Smelter",
        fire_support_base: "Fire Support Base",
        pillbox: "Pillbox",
        elerium_cannon: "Elerium Cannon",
        elerium_containment: "Elerium Containment",
        ambrosia: "Ambrosia",
        eternal_bank: "Eternal Wealth",
        wisdom: "Wisdom of the Ancients",
        rushmore: "Mount Humanmore",
        reincarnation: "Reincarnation Machine",
        otherworldly_cement: "Edenic Cement",
        ancient_crafters: "Ancient Crafters",
        spirit_syphon: "Spirit Syphon",
        spirit_capacitor: "Spirit Capacitor",
        suction_force: "Suction Force",
        soul_compactor: "Soul Compactor",
        tomb: "Tomb of the Dead God",
        energy_drain: "Energy Drain",
        divine_infuser: "Divine Infuser"
    },
    "Outer Solar System": {
        alien_biotech: { name: "Alien Biotech", suffix: "True Path" },
        zero_g_lab: { name: "Zero Gravity Lab", suffix: "True Path" },
        operating_base: { name: "Operating Base", suffix: "True Path" },
        munitions_depot: { name: "Munitions Depot", suffix: "True Path" },
        fob: { name: "Forward Operating Base", suffix: "True Path" },
        bac_tanks_tp: { name: "BAC Tank", suffix: "True Path" },
        medkit: { name: "Advanced Medkits", suffix: "True Path" },
        sam_site: { name: "Planetary Defenses", suffix: "True Path" },
        data_cracker: { name: "Data Cracker", suffix: "True Path" },
        ai_core_tp: { name: "AI Supercore", suffix: "True Path" },
        ai_optimizations: { name: "AI Optimizations", suffix: "True Path" },
        synthetic_life: { name: "Synthetic Life", suffix: "True Path" },
        protocol66: { name: "Protocol 66", suffix: "Warning, True Path" },
        protocol66a: { name: "Protocol 66", suffix: "True Path" },
        terraforming_tp: { name: "Terraforming", suffix: "Orbital Decay, True Path" },
        quantium: { name: "Quantium", suffix: "True Path" },
        anitgrav_bunk: { name: "Anti-Grav Bunks", suffix: "True Path" },
        long_range_probes: { name: "Long Range Probes", suffix: "True Path" },
        strange_signal: { name: "Strange Signal", suffix: "True Path" },
        data_analysis: { name: "Encrypted Data Analysis", suffix: "True Path" },
        mass_relay: { name: "Mass Relay", suffix: "True Path" },
        nav_data: { name: "Navigation Data", suffix: "True Path" },
        sensor_logs: { name: "Tau Ceti Data", suffix: "True Path" },
        dronewar: { name: "Drone Warfare", suffix: "True Path" },
        drone_tank: { name: "AI Drone Tanks", suffix: "True Path" },
        stanene_tp: { name: "Stanene", suffix: "True Path" },
        graphene_tp: { name: "Graphene", suffix: "True Path" },
        virtual_reality_tp: { name: "Virtual Reality", suffix: "True Path" },
        electrolysis: { name: "Electrolysis", suffix: "True Path" },
        storehouse: { name: "Titan Storage Facility", suffix: "True Path" },
        adamantite_vault_tp: { name: "Adamantite Vault", suffix: "True Path" },
        titan_bank: { name: "Titan Banking", suffix: "True Path" },
        hydrogen_plant: { name: "Hydrogen Power", suffix: "True Path" },
        water_mining: { name: "Water Mining", suffix: "True Path" },
        mercury_smelting: { name: "Solar Smelting", suffix: "True Path" },
        iridium_smelting: { name: "Iridium Smelting", suffix: "True Path" },
        adamantite_crates: { name: "Adamantite Crates", suffix: "True Path" },
        adamantite_containers_tp: { name: "Adamantite Containers", suffix: "True Path" },
        quantium_containers: { name: "Quantium Containers", suffix: "True Path" },
        reinforced_shelving: { name: "Reinforced Shelving", suffix: "True Path" },
        garage_shelving: { name: "Quantium Garage Shelving", suffix: "True Path" },
        warehouse_shelving: { name: "Automated Warehousing System", suffix: "True Path" },
        elerium_extraction: { name: "Elerium Extraction", suffix: "True Path" },
        orichalcum_panels_tp: { name: "Orichalcum Panels", suffix: "True Path" },
        shipyard: { name: "Ceres Ship Yard", suffix: "True Path" },
        ship_lasers: { name: "Ship Lasers", suffix: "True Path" },
        pulse_lasers: { name: "Ship Pulse Lasers", suffix: "True Path" },
        ship_plasma: { name: "Ship Plasma Beams", suffix: "True Path" },
        ship_phaser: { name: "Ship Phasers", suffix: "True Path" },
        ship_disruptor: { name: "Ship Disruptor", suffix: "True Path" },
        destroyer_ship: { name: "Destroyer", suffix: "True Path" },
        cruiser_ship_tp: { name: "Cruiser", suffix: "True Path" },
        h_cruiser_ship: { name: "Battlecruiser", suffix: "True Path" },
        dreadnought_ship: { name: "Dreadnought", suffix: "True Path" },
        pulse_engine: { name: "Pulse Drive", suffix: "True Path" },
        photon_engine: { name: "Photon Drive", suffix: "True Path" },
        vacuum_drive: { name: "Vacuum Drive", suffix: "True Path" },
        ship_fusion: { name: "Fusion Generator", suffix: "True Path" },
        ship_elerium: { name: "Elerium Generator", suffix: "True Path" },
        quantum_signatures: { name: "Quantum Signatures", suffix: "True Path" }
    },
    "Tau Ceti": {
        bolognium_crates_tp: { name: "Bolognium Crates", suffix: "True Path" },
        unobtainium_containers: { name: "Unobtainium Containers", suffix: "True Path" },
        interstellar_drive: { name: "Interstellar Drive", suffix: "True Path" },
        alien_outpost: { name: "Alien Outpost", suffix: "True Path" },
        jumpgates: { name: "Jump Gates", suffix: "True Path" },
        system_survey: { name: "Tau Survey", suffix: "True Path" },
        repository: { name: "Repository", suffix: "True Path" },
        fusion_generator: { name: "Nuclear Fusion", suffix: "True Path" },
        tau_cultivation: { name: "Tau Ceti Cultivation", suffix: "True Path" },
        tau_manufacturing: { name: "Tau Ceti Manufacturing", suffix: "True Path" },
        weasels: { name: "Weasels", suffix: "True Path" },
        jeff: { name: "Contact Jeff", suffix: "True Path" },
        womling_fun: { name: "Womling Entertainment", suffix: "True Path" },
        womling_lab: { name: "Womling Science", suffix: "True Path" },
        womling_mining: { name: "Womling Dirt Excavation", suffix: "True Path" },
        womling_firstaid: { name: "Womling First Aid", suffix: "True Path" },
        womling_logistics: { name: "Womling Logistics", suffix: "True Path" },
        womling_repulser: { name: "Womling Repulser Pad", suffix: "True Path" },
        womling_farming: { name: "Womling Farming", suffix: "True Path" },
        womling_housing: { name: "Womling Housing", suffix: "True Path" },
        womling_support: { name: "Womling Support", suffix: "True Path" },
        womling_recycling: { name: "Womling Recycling", suffix: "True Path" },
        asteroid_analysis: { name: "Asteroid Data Analysis", suffix: "True Path" },
        shark_repellent: { name: "Shark Repellent", suffix: "True Path" },
        belt_mining: { name: "Tau Ceti Belt Mining", suffix: "True Path" },
        adv_belt_mining: { name: "Advanced Belt Mining", suffix: "True Path" },
        space_whaling: { name: "Space Whaling", suffix: "True Path" },
        infectious_disease_lab: { name: "Infectious Disease Lab", suffix: "True Path" },
        isolation_protocol: { name: "Isolation Protocol", suffix: "True Path" },
        focus_cure: { name: "Focus Cure", suffix: "True Path" },
        decode_virus: { name: "Decode Virus", suffix: "True Path" },
        vaccine_campaign: { name: "Vaccination Campaign", suffix: "True Path" },
        vax_strat1: { name: "Propaganda Campaign", suffix: "True Path" },
        vax_strat2: { name: "Force Vaccination", suffix: "True Path" },
        vax_strat3: { name: "Show the Science", suffix: "True Path" },
        vax_strat4: { name: "Secret Vaccination", suffix: "True Path" },
        cloning: { name: "Cloning Facility", suffix: "True Path" },
        clone_degradation: { name: "Clone Degradation", suffix: "True Path" },
        digital_paradise: { name: "Digital Paradise", suffix: "True Path" },
        ringworld: { name: "Design a Ringworld", suffix: "True Path" },
        iso_gambling: { name: "Pit Bosses", suffix: "True Path" },
        outpost_boost: { name: "Alien Outpost Device", suffix: "True Path" },
        cultural_center: { name: "Cultural Center", suffix: "True Path" },
        outer_tau_survey: { name: "Survey Outer Planet", suffix: "True Path" },
        alien_research: { name: "Alien Research", suffix: "True Path" },
        womling_gene_therapy: { name: "Womling Gene Therapy", suffix: "True Path" },
        food_culture: { name: "Sell fruitcake", suffix: "True Path" },
        advanced_refinery: { name: "Advanced Ore Refinery", suffix: "True Path" },
        advanced_pit_mining: { name: "Advanced Pit Mining", suffix: "True Path" },
        useless_junk: { name: "Useless Junk", suffix: "True Path" },
        advanced_asteroid_mining: { name: "Advanced Asteroid Mining", suffix: "True Path" },
        advanced_material_synthesis: { name: "Advanced Material Synthesis", suffix: "True Path" },
        matrioshka_brain: { name: "Matrioshka Brain", suffix: "True Path" },
        ignition_device: { name: "Ignition Device", suffix: "True Path" },
        replicator: { name: "Matter Replicator", suffix: "Lone Survivor, True Path" },
        womling_unlock: { name: "Meet The Neighbors", suffix: "Lone Survivor, True Path" },
        garden_of_eden: { name: "Garden of Eden", suffix: "True Path" }
    }
});
